Cliente c1 = new Cliente();
//Console.WriteLine("Informe o nome do cliente: ");
//c1.DefinirNome(Console.ReadLine());
//Console.WriteLine("Informe o endereço do cliente: ");
//c1.DefinirEndereco(Console.ReadLine());
//Console.WriteLine("Informe o sexo do cliente [M][F]: ");
//c1.DefinirSexo(Console.ReadLine());
//Console.WriteLine("Informe o telefone do cliente: ");
//c1.DefinirTelefone(Console.ReadLine());
//Console.WriteLine("Informe o salário do cliente: ");
//c1.DefinirSalario(float.Parse(Console.ReadLine()));
//Console.WriteLine("Informe a data de nascimento do cliente: ");
//c1.DefinirNascimento(DateOnly.Parse(Console.ReadLine()));
//Console.WriteLine("Informe o numero da conta: ");
//c1.DefinirConta(int.Parse(Console.ReadLine()));
//Console.WriteLine("==================== CONTA ====================");
//c1.ImprimirContaPessoa();
Console.WriteLine("====================================================");
Funcionario f1 = new Funcionario();
Console.WriteLine("Informe o nome do funcionario: ");
f1.DefinirNome(Console.ReadLine());
Console.WriteLine("Informe o endereço do funcionario: ");
f1.DefinirEndereco(Console.ReadLine());
Console.WriteLine("Informe o sexo do funcionario [M][F]: ");
f1.DefinirSexo(Console.ReadLine());
Console.WriteLine("Informe o telefone do funcionario: ");
f1.DefinirTelefone(Console.ReadLine());
Console.WriteLine("Informe o salário do funcionario: ");
f1.DefinirSalario(float.Parse(Console.ReadLine()));
Console.WriteLine("Informe a data de nascimento do funcionario: ");
f1.DefinirNascimento(DateOnly.Parse(Console.ReadLine()));
Console.WriteLine("Informe o codigo do funcionario: ");
f1.DefinirCodigo(int.Parse(Console.ReadLine()));
Console.WriteLine("Informe o cargo do funcionario: ");
f1.DefinirCargo(Console.ReadLine());
Console.WriteLine("==================== Funcionario ====================");
f1.ImprimirFuncionario();

